export const projects = [
  {
    id: 1,
    title: "Real-time Analytics Platform",
    description:
      "Scalable platform processing 10TB+ daily data with sub-second query response times using Apache Kafka, Spark, and ClickHouse.",
    category: "data-engineering",
    technologies: ["Apache Kafka", "Spark", "ClickHouse", "Python", "Docker", "Kubernetes"],
    features: [
      "Real-time data ingestion from 100+ sources",
      "Sub-second query response times",
      "Auto-scaling infrastructure",
      "Custom alerting system",
    ],
    icon: "📊",
    githubUrl: "https://github.com/algorhythmic",
    liveUrl: "https://analytics.daviddunn.tech",
    demoUrl: "https://demo.analytics.daviddunn.tech",
  },
  {
    id: 2,
    title: "ML Pipeline Orchestrator",
    description:
      "End-to-end ML pipeline management system with automated model training, validation, and deployment capabilities.",
    category: "machine-learning",
    technologies: ["Python", "MLflow", "Airflow", "TensorFlow", "AWS SageMaker", "Terraform"],
    features: [
      "Automated model training & validation",
      "A/B testing framework",
      "Model versioning & rollback",
      "Performance monitoring",
    ],
    icon: "🤖",
    githubUrl: "https://github.com/algorhythmic",
    demoUrl: "https://ml-demo.daviddunn.tech",
  },
  {
    id: 3,
    title: "Data Visualization Dashboard",
    description:
      "Interactive dashboard built with React and D3.js for exploring complex datasets with custom visualizations and filters.",
    category: "web-apps",
    technologies: ["React", "D3.js", "TypeScript", "Node.js", "PostgreSQL", "Redis"],
    features: [
      "Interactive data exploration",
      "Custom visualization components",
      "Real-time data updates",
      "Export capabilities",
    ],
    icon: "📈",
    githubUrl: "https://github.com/algorhythmic",
    liveUrl: "https://dataviz.daviddunn.tech",
    demoUrl: "https://demo.daviddunn.tech",
  },
  {
    id: 4,
    title: "ETL Pipeline Framework",
    description:
      "Reusable ETL framework with built-in data quality checks, error handling, and monitoring for enterprise data workflows.",
    category: "data-engineering",
    technologies: ["Python", "Apache Airflow", "dbt", "Snowflake", "Great Expectations", "Grafana"],
    features: [
      "Automated data quality checks",
      "Error handling & recovery",
      "Performance monitoring",
      "Configurable transformations",
    ],
    icon: "🔄",
    githubUrl: "https://github.com/algorhythmic",
  },
  {
    id: 5,
    title: "Customer Analytics API",
    description:
      "High-performance REST API serving customer analytics with caching, rate limiting, and comprehensive documentation.",
    category: "web-apps",
    technologies: ["FastAPI", "Python", "Redis", "PostgreSQL", "Docker", "OpenAPI"],
    features: [
      "Sub-100ms response times",
      "Comprehensive API documentation",
      "Rate limiting & authentication",
      "Automated testing suite",
    ],
    icon: "🚀",
    githubUrl: "https://github.com/algorhythmic",
    liveUrl: "https://api.daviddunn.tech",
    demoUrl: "https://docs.api.daviddunn.tech",
  },
  {
    id: 6,
    title: "Predictive Maintenance System",
    description:
      "IoT data processing system with machine learning models for predicting equipment failures and optimizing maintenance schedules.",
    category: "machine-learning",
    technologies: ["Python", "TensorFlow", "Apache Kafka", "InfluxDB", "Grafana", "MQTT"],
    features: [
      "Real-time IoT data processing",
      "Predictive failure detection",
      "Maintenance optimization",
      "Alert system integration",
    ],
    icon: "⚙️",
    githubUrl: "https://github.com/algorhythmic",
  },
  {
    id: 7,
    title: "Business Intelligence Suite",
    description:
      "Comprehensive BI platform with automated reporting, KPI tracking, and executive dashboards for data-driven decision making.",
    category: "analytics",
    technologies: ["Python", "Tableau", "SQL", "dbt", "Snowflake", "Apache Superset"],
    features: [
      "Automated report generation",
      "Executive dashboards",
      "KPI tracking & alerts",
      "Self-service analytics",
    ],
    icon: "📋",
    githubUrl: "https://github.com/algorhythmic",
    demoUrl: "https://bi-demo.daviddunn.tech",
  },
  {
    id: 8,
    title: "Data Lake Architecture",
    description:
      "Scalable data lake implementation on AWS with automated data cataloging, governance, and security controls.",
    category: "data-engineering",
    technologies: ["AWS S3", "AWS Glue", "Apache Spark", "Terraform", "Python", "Apache Atlas"],
    features: [
      "Automated data cataloging",
      "Data governance framework",
      "Security & access controls",
      "Cost optimization",
    ],
    icon: "🏗️",
    githubUrl: "https://github.com/algorhythmic",
  },
  {
    id: 9,
    title: "Social Media Analytics",
    description:
      "Real-time social media monitoring and sentiment analysis platform with trend detection and influencer identification.",
    category: "analytics",
    technologies: ["Python", "Apache Kafka", "Elasticsearch", "Kibana", "NLTK", "spaCy"],
    features: [
      "Real-time sentiment analysis",
      "Trend detection algorithms",
      "Influencer identification",
      "Custom reporting dashboard",
    ],
    icon: "📱",
    githubUrl: "https://github.com/algorhythmic",
    demoUrl: "https://social-demo.daviddunn.tech",
  },
]
